/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cn.com.cybertech.pm.media.audio;

public class Amrnb {
  public static void Decoder_init() {
    AmrnbJNI.Decoder_init();
  }

  public static void Decoder_exit() {
    AmrnbJNI.Decoder_exit();
  }

  public static void Decoder_decode(byte[] in, short[] out) {
    AmrnbJNI.Decoder_decode(in, out);
  }

}
