/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cn.com.cybertech.pm.media.audio;

public final class Mode {
  public final static Mode MR475 = new Mode("MR475", AmrnbJNI.MR475_get());
  public final static Mode MR515 = new Mode("MR515");
  public final static Mode MR59 = new Mode("MR59");
  public final static Mode MR67 = new Mode("MR67");
  public final static Mode MR74 = new Mode("MR74");
  public final static Mode MR795 = new Mode("MR795");
  public final static Mode MR102 = new Mode("MR102");
  public final static Mode MR122 = new Mode("MR122");
  public final static Mode MRDTX = new Mode("MRDTX");
  public final static Mode N_MODES = new Mode("N_MODES");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static Mode swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + Mode.class + " with value " + swigValue);
  }

  private Mode(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private Mode(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private Mode(String swigName, Mode swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static Mode[] swigValues = { MR475, MR515, MR59, MR67, MR74, MR795, MR102, MR122, MRDTX, N_MODES };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

